baseURL = "https://macdavid313.xyz/"
languageCode = "en-us"
theme = "smol"
title = "gty"

# Parameters
[params]
    author = "Tianyu Gu"
    subtitle = "You gotta go away to come back."
    dateFmt = "Jan 2, 2006, Monday"

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "posts"
        url = "/posts/"
        weight = 1

  [[menu.main]]
        identifier = "tags"
        name = "tags"
        url = "/tags/"
        weight = 2

  [[menu.main]]
        identifier = "about"
        name = "about"
        url = "/about/"

# Footer
  [[menu.footer]]
        name = "email"
        url = "mailto:macdavid313@gmail.com"
        weight = 1

  [[menu.footer]]
        name = "github"
        url = "https://github.com/macdavid313"
        weight = 2

  [[menu.footer]]
        name = "PGP"
        url = "/assets/pgp-public.txt"
        weight = 3
