baseURL = "https://macdavid313.xyz/"
languageCode = "en-us"
title = "Tianyu Gu Home Page"

theme = "vncnt-hugo"

[params]
  author = "顾天宇 (Tianyu Gu)"
  email = "macdavid313@gmail.com"
  description = "Tianyu Gu's Home Page"
  bio = "欢迎！Welcome!  \nI currently live in Sydney, Australia and work as a Software Developer."
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/macdavid313"
    skype = "https://join.skype.com/invite/PnDVYxWL5k5a"
    telegram = "https://t.me/macdavid313"
